[project]
name = "mcp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chromedriver-py>=143.0.7499.42",
    "mcp[cli]>=1.21.1",
    "requests>=2.32.5",
]
